name: Backend Tests

on:
  pull_request:
    branches: [ main , stable ]

jobs:
  Backend-ci-test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /

    strategy:
      matrix:
        node-version: [18.x]


    steps:
    - uses: actions/checkout@v3
    - name: Build and start Docker containers
    - run: docker-compose -f docker-compose.yml -f development.yml up --build
