name: Docker-test

on:
  pull_request:
    branches: [ main , test ]
    
defaults:
  run:
    working-directory: ./Application

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker images
      uses: docker/build-push-action@v2

    - name: Start Docker containers
    - uses: docker/compose-action@1.2.0
    - run: docker-compose -f docker-compose.yml -f development.yml up --build

    - name: Run tests
      run: docker-compose -f docker-compose.yml run --rm server sh -c "python manage.py test"

    - name: Stop Docker containers
      uses: docker/compose-action@1.2.0


