name: Docker-test

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v2.2.1
        with:
          compose-version: 2.0.0

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml -f development.yml up --build  

      - name: Run Django tests
        run: |
          docker-compose -f docker-compose.yml run --rm server sh -c "python manage.py test"


