name: Docker Compose Build and Deploy

on:
  push:
    branches:
      - main
      - Docker-test

jobs:
  build:
    runs-on: ubuntu-latest
    
    
steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1
  - name: Log in to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.kf21667@bristol.ac.uk }}
      password: ${{ secrets.Uzumymw123 }}
  - name: Build and push Docker image
    uses: docker/build-push-action@v2
    with:
      context: .
      file: Dockerfile
      push: true
      tags: username/repo:latest
  - name: Start containers
    run: docker-compose -f docker-compose.yml -f development.yml up --build
