name: Docker-test

on:
  pull_request:
    branches: [ main , test ]
    
defaults:
  run:
    working-directory: ./Application

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/compose-action@v2

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml -f development.yml up --build  

      - name: Run Django tests
        run: |
          docker-compose -f docker-compose.yml run --rm server sh -c "python manage.py test"
          
      - name: Stop Docker containers
        run: docker-compose down


